{
    "CreateLinks": [],
    "OnFailure": "/bookshop-mdk/Actions/CreateEntityFailureMessage.action",
    "OnSuccess": "/bookshop-mdk/Actions/CreateEntitySuccessMessage.action",
    "Properties": {
        "ID": "#Control:ID/#Value",
        "name": "#Control:name/#Value",
        "imageType": "#Control:imageType/#Value"
    },
    "Target": {
        "EntitySet": "BookImages",
        "Service": "/bookshop-mdk/Services/service1.service"
    },
    "ActionResult": {
        "_Name": "create"
    },
    "ShowActivityIndicator" : true,
    "_Type": "Action.Type.ODataService.CreateEntity"
}