{
 	"Service": "/bookshop-mdk/Services/service1.service",
 "_Type": "Action.Type.OfflineOData.Upload",
  "ShowActivityIndicator" : true,
  "OnSuccess": "/bookshop-mdk/Actions/Service/Download.action",
  "OnFailure": "/bookshop-mdk/Actions/Service/UploadFailureMessage.action"
}